# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ConsultarRegionAdministrativa.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ConsultarRegionAdministrativa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ConsultarRegionAdministrativa.proto\x12\x1d\x43onsultarRegionAdministrativa\"M\n\x16GetCodigoRegionRequest\x12\x1a\n\x12nombreDepartamento\x18\x01 \x01(\t\x12\x17\n\x0fnombreMunicipio\x18\x02 \x01(\t\"N\n\x17GetCodigoRegionResponse\x12\x1a\n\x12\x63odigoDepartamento\x18\x01 \x01(\t\x12\x17\n\x0f\x63odigoMunicipio\x18\x02 \x01(\t2\xa9\x01\n$ConsultarRegionAdministrativaService\x12\x80\x01\n\x0fGetCodigoRegion\x12\x35.ConsultarRegionAdministrativa.GetCodigoRegionRequest\x1a\x36.ConsultarRegionAdministrativa.GetCodigoRegionResponseB.\xaa\x02+GrpcApiService.enrolamientoProductos.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ConsultarRegionAdministrativa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002+GrpcApiService.enrolamientoProductos.Protos'
  _globals['_GETCODIGOREGIONREQUEST']._serialized_start=70
  _globals['_GETCODIGOREGIONREQUEST']._serialized_end=147
  _globals['_GETCODIGOREGIONRESPONSE']._serialized_start=149
  _globals['_GETCODIGOREGIONRESPONSE']._serialized_end=227
  _globals['_CONSULTARREGIONADMINISTRATIVASERVICE']._serialized_start=230
  _globals['_CONSULTARREGIONADMINISTRATIVASERVICE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
